import { sqliteTable, integer, real, text } from 'drizzle-orm/sqlite-core';

export const cities = sqliteTable('cities', {
    name: text("name").notNull(),
    state: text("state").notNull(),
    costOfLivingIndex: real("costOfLivingIndex").notNull(),
    medianRent: integer("medianRent").notNull(),
    medianHomePrice: integer("medianHomePrice").notNull(),
    medianIncome: integer("medianIncome").notNull(),
    incomeToCostRatio: real("incomeToCostRatio").notNull(),
    crimeIndex: real("crimeIndex").notNull(),
    violentCrimeIndex: real("violentCrimeIndex").notNull(),
    propertyCrimeRate: real("propertyCrimeRate").notNull(),
    walkabilityScore: integer("walkabilityScore").notNull(),
    bikeabilityScore: integer("bikeabilityScore").notNull(),
    transitScore: integer("transitScore").notNull(),
    commuteTime: real("commuteTime").notNull(),
    trafficCongestionIndex: real("trafficCongestionIndex").notNull(),
    averageAnnualTemperature: real("averageAnnualTemperature").notNull(),
    airQualityIndex: real("airQualityIndex").notNull(),
    greenSpacePerCapita: real("greenSpacePerCapita").notNull(),
    naturalDisasterRisk: real("naturalDisasterRisk").notNull(),
    healthcareAccessScore: real("healthcareAccessScore").notNull(),
    educationIndex: real("educationIndex").notNull(),
    universityProximity: integer("universityProximity").notNull(),
    diversityIndex: real("diversityIndex").notNull(),
    politicalLeaning: text("politicalLeaning").notNull(),
    nightlifeIndex: integer("nightlifeIndex").notNull(),
    religiousInstitutionsPerCapita: real("religiousInstitutionsPerCapita").notNull(),
    jobMarketIndex: real("jobMarketIndex").notNull(),
    unemploymentRate: real("unemploymentRate").notNull(),
    startupEcosystemRank: integer("startupEcosystemRank").notNull(),
});
